spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: aa
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
